### ISSUE TITLE
Add metadata for SEO

### ISSUE THREAD

**Issue by steve-bang** [steve-bang/pomotimer-nextjs#4]

**Comment by Samuelarag1** [comment]
i send you a pr with my changes but i dont have the real domain to get the perfect robots.txt or sitemap.xml

**Comment by steve-bang** [comment]
> i send you a pr with my changes but i dont have the real domain to get the perfect robots.txt or sitemap.xml

Thanks for your helping. Can you commit change for this issue? I appreciate about that. Let's become contributors together for this project.
